import { baseAbilityScoreBlock } from '../shared/AbilityScores.js';
export const characterActorType = 'CharacterActor';
export const emptyCharacterData = {
    type: characterActorType,
    class: '',
    abilities: baseAbilityScoreBlock,
    ac: 10,
    bab: 0,
    background: '',
    coinage: {
        iron: 0,
        copper: 0,
        silver: 0,
        gold: 0,
        platinum: 0,
    },
    exp: { max: 0, value: 0 },
    features: '',
    fortune: 0,
    goals: [],
    heightWeight: '',
    hp: { max: 10, value: 10 },
    initiative: '1d10',
    mab: 0,
    mainNotes: '',
    maxWeight: 0,
    misc: [],
    notes: '',
    rab: 0,
    saves: {
        Fortitude: 0,
        Will: 0,
        Luck: 0,
        Reflex: 0,
    },
    skills: [],
    slots: 0,
    speed: 0,
    traits: '',
    treasure: '',
};
